name: Cron Job
on:
    schedule:
        - cron: "* * * * *"
jobs:
    cron-job:
        runs-on: ubuntu-latest
        steps:
            - name: Cron Job Testing
              run: |
                  echo "Cron-Job I"
                  echo "Available testing "
