name: First-Workflow

on: [push]
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: first Workflow III
              run: |
                  echo "hello"
                  echo "hello again !!!"
