name: manual workflow
on:
    workflow_dispatch:
jobs:
    second-manual-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: second manual A automate
              run: |
                  echo "Linux Shell Scriping"
                  echo "manual running"
